#!/bin/ksh

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   work dir that local script can use
# Output:
#   Return code of 0=success or 1=failure   or 2=job submitted
#
# Notes:
#   If this script is called from swtest, then swtest requires 
#   SW_WORKDIR to be set.  Then swtest adds a unique path to what 
#   user gave swtest (action+timestamp+build) and provides this
#   script with a uniquely valued SW_WORKDIR.  swtest will
#   automatically remove this unique workspace when retest is done.
##################################################################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
#clear out status file since re-testing
rm -f status 

cp -a $SRCDIR $SW_WORKDIR

cd $SW_WORKDIR/$SRCDIR
sed -i "s/\$\${dir}\$\$tst/aprun -n 1 \$\${dir}\$\$tst/" */Makefile

cd $SW_WORKDIR

cat > gsl.pbs << EOF
#PBS -j oe
#PBS -l size=16,walltime=0:55:00
#PBS -A UT-SUPPORT
#PBS -W umask=002
set -o verbose

cd \$PBS_O_WORKDIR 
cd $SRCDIR

source ${SW_BLDDIR}/remodule
make check 2>&1 | tee test.log
if [ $? -ne 0 ] ; then
  echo "$SRCDIR make test failed "
  echo unverified > $SW_BLDDIR/status
fi

testspassed1=\`grep -G "All [0123456789] tests" test.log | awk '{total += \$2} END {print total}'\`
testspassed2=\`grep -G "[0123456789] test passed" test.log | awk '{total += \$1} END {print total}'\`
((testspassed=testspassed1+testspassed2))
if [[ \$testspassed -lt 45 ]]; then
  # error
  echo \$testspassed out of 45 tests passed!
  echo unverified > $SW_BLDDIR/status
else
  echo All \$testspassed tests passed!
  echo verified > $SW_BLDDIR/status
fi

cd \$PBS_O_WORKDIR 

#-- Log and Cleanup 
JOBID=\`echo \$PBS_JOBID | cut -d "." -f1 \`
cat \$PBS_JOBNAME.o\$JOBID >> ${SW_BLDDIR}/test.log
chmod 664 ${SW_BLDDIR}/status
chmod 664 ${SW_BLDDIR}/test.log
rm -f ${SW_BLDDIR}/.running

############################### if this far, return 0
exit 0

EOF

qsub gsl.pbs > $SW_BLDDIR/.running
if [ $? -ne 0 ] ; then
  echo "Error submitting job"
  rm -f .running
  exit 1
else
  echo "Job submitted"
  cat ${SW_BLDDIR}/.running
  exit 2
fi

cd ../

############################### if this far, return 0
exit 0
