#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready
#exit 3

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/bash
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
set -o verbose
rm -rf bin lib include doc share man etc libexec info

#clear out status and old SRCDIR file since re-making
rm -f status
rm -rf $SRCDIR

tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/${SRCDIR}-b.tar.gz

cd $SRCDIR

cp make.inc.mkl-icc make.inc
sed -i 's/= Fermi/= Kepler/' make.inc

make clean

#./configure --prefix=$SW_BLDDIR \
#--disable-shared
#--disable-fortran-compiler-check
#--host=x86_64-unknown-linux-gnu
#if [ $? -ne 0 ] ; then
#  echo "$PACKAGE configure failed"
#  exit 1
#fi

make 
  if [ $? -ne 0 ] ; then
    echo "$PACKAGE make failed"
    exit 1
  fi

make install prefix=$SW_BLDDIR
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

#-- Manually copy generated .mod files for Fortran interface since
#   "make install" does not do it apparently
cp include/*.mod $SW_BLDDIR/include

cd ../

#-- Write pkg-config file
mkdir -p $SW_BLDDIR/lib/pkgconfig
cat > $SW_BLDDIR/lib/pkgconfig/${PACKAGE}.pc << EOF
prefix=$SW_BLDDIR
includedir=\${prefix}/include
libdir=\${prefix}/lib

Name: ${PACKAGE}
Description: ${PACKAGE} Library
URL: http://icl.cs.utk.edu/magma/
Version: $VERSION
Cflags: -I\${includedir}  
Libs: -L\${libdir} -lmagma
Requires: cuda
EOF


############################### if this far, return 0
exit 0
