#!/bin/ksh

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  

set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin include doc share man etc libexec info lib

# clear out status file since re-making
rm -f status test.log

export PATH=${SW_BLDDIR}/bin:${PATH}
export LDFLAGS="-Wl,-rpath,${SW_BLDDIR}/lib,-rpath,${MKL_DIR}/lib/intel64"
echo $LDFLAGS
unset PYTHONPATH #-- prevent interference from ALTD's python

source rebuild_python

echo "Test which python3:"
which python3

source rebuild_setuptools
source rebuild_nose
source rebuild_numpy
source rebuild_scipy
##source rebuild_scientificpython  -- no support for python 3.3
source rebuild_matplotlib
source rebuild_cython
##source rebuild_mpi4py            -- no support for python 3.3
##source rebuild_numexpr           -- no support for python 3.3
##source rebuild_pytables          -- no support for python 3.3
##source rebuild_pyfits            -- no support for python 3.3
source rebuild_lxml
#source rebuild_pynio             -- no support for python 3.3

############################### if this far, return 0
exit 0
