#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin lib include doc share man etc libexec info

PREFIX=${SW_BLDDIR}/${PACKAGE}

#clear out status and old SRCDIR file since re-making
rm -f status
rm -rf $SRCDIR $PREFIX
     
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$SRCDIR.tar.bz2

chmod -R u+rw $SRCDIR
cd $SRCDIR

./install.sh -d ${PREFIX} -f -u linux-suse10-amd64
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd ${PREFIX}
. ./shrc

#-- write SPEC config
CONFIG_NAME=$(basename $SW_BLDDIR)
cat > ${PREFIX}/config/${CONFIG_NAME}.cfg << EOF

ignore_errors = yes
tune          = base
size          = ref
ext           = $HOSTNAME
output_format = asc
reportable    = 1
teeout        = yes
teerunout     = yes

default=default=default=default:
CC           = gcc
CXX          = g++
FC           = gfortran

default=base=default=default:
COPTIMIZE    = -O3
CXXOPTIMIZE  = -O3
FOPTIMIZE    = -O3

default=base=default=default:
notes25= PORTABILITY=-DSPEC_CPU_LP64 is applied to all benchmarks in base.
PORTABILITY = -DSPEC_CPU_LP64

400.perlbench=default=default=default:
CPORTABILITY   = -DSPEC_CPU_LINUX_X64 -std=gnu89

462.libquantum=default=default=default:
CPORTABILITY   =  -DSPEC_CPU_LINUX

483.xalancbmk=default=default=default:
CXXPORTABILITY = -DSPEC_CPU_LINUX

481.wrf=default=default=default:
CPORTABILITY   = -DSPEC_CPU_CASE_FLAG -DSPEC_CPU_LINUX
EOF
ln -s ${PREFIX}/config/${CONFIG_NAME}.cfg ${PREFIX}/config/default.cfg

#-- Build all binaries
runspec --action=build --tune=base all

############################### if this far, return 0
exit 0
