#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready
#exit 3

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin lib include doc share man etc libexec info

#clear out status and old SRCDIR file since re-making
rm -f status
rm -rf $SRCDIR

export PATH=$SW_BLDDIR/bin:${PATH}
export LD_LIBRARY_PATH=$SW_BLDDIR/lib:${LD_LIBRARY_PATH}
export LIBRARY_PATH=$SW_BLDDIR/lib:${LIBRARY_PATH}
export CPATH=$SW_BLDDIR/include:${CPATH}
export PKG_CONFIG_PATH=$SW_BLDDIR/lib/pkgconfig:$PKG_CONFIG_PATH


echo "Building gstreamer"
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$GSTREAMER_SRC.tar.xz

cd $GSTREAMER_SRC

./configure --prefix=$SW_BLDDIR
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_SRC configure failed"
  exit 1
fi

make
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_SRC make failed"
  exit 1
fi

make install
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_SRC install failed"
  exit 1
fi

cd $SW_BLDDIR

echo "Building gstreamer plugin"
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$GSTREAMER_PLUGIN_SRC.tar.gz

cd $GSTREAMER_PLUGIN_SRC

./configure --prefix=$SW_BLDDIR
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_PLUGIN_SRC configure failed"
  exit 1
fi

make
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_PLUGIN_SRC make failed"
  exit 1
fi

make install
if [ $? -ne 0 ] ; then
  echo "$GSTREAMER_PLUGIN_SRC install failed"
  exit 1
fi

cd $SW_BLDDIR

tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$SRCDIR.tar.bz2

cd $SRCDIR/${PACKAGE}
python2.7 build-wxpython.py --wxpy_installdir=$SW_BLDDIR 
#--installdir=$SW_BLDDIR
if [ $? -ne 0 ] ; then
  echo "${PACKAGE} install failed"
  exit 1
fi



cd $SW_BLDDIR


############################### if this far, return 0
exit 0
