#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready
#exit 3

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin lib include doc share man etc libexec info

#clear out status and old SRCDIR file since re-making
rm -f status
rm -rf $SRCDIR

tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$SRCDIR.tar.gz

cd $SRCDIR


#
# Build Parallel version-Single precision
#
mkdir buildParS
cd buildParS
cmake ../ \
      -DGMX_MPI=ON \
      -DCMAKE_INSTALL_PREFIX=$SW_BLDDIR \
      -DGMX_BUILD_OWN_FFTW=ON  \
      -DCMAKE_BUILD_TYPE=Release \
      -DGMX_GPU=OFF \
      -DGMX_X11=OFF \
      -DGMX_EXTERNAL_BLAS=no \
      -DGMX_EXTERNAL_LAPACK=no \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_CXX_COMPILER=mpicxx \
      -DGMX_DEFAULT_SUFFIX=ON

if [ $? -ne 0 ] ; then
  echo "$PACKAGE configure failed"
  exit 1
fi

make
  if [ $? -ne 0 ] ; then
    echo "$PACKAGE make failed"
    exit 1
  fi

make install
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd ..

mkdir buildParD
cd buildParD
cmake ../ \
      -DGMX_MPI=ON \
      -DCMAKE_INSTALL_PREFIX=$SW_BLDDIR \
      -DGMX_BUILD_OWN_FFTW=ON  \
      -DCMAKE_BUILD_TYPE=Release \
      -DGMX_GPU=OFF \
      -DGMX_X11=OFF \
      -DGMX_EXTERNAL_BLAS=no \
      -DGMX_EXTERNAL_LAPACK=no \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DGMX_DOUBLE=ON \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_CXX_COMPILER=mpicxx \
      -DGMX_DEFAULT_SUFFIX=ON

if [ $? -ne 0 ] ; then
  echo "$PACKAGE configure failed"
  exit 1
fi

make
  if [ $? -ne 0 ] ; then
    echo "$PACKAGE make failed"
    exit 1
  fi

make install
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd ..


mkdir buildSerD
cd buildSerD
cmake ../ \
      -DGMX_MPI=OFF \
      -DCMAKE_INSTALL_PREFIX=$SW_BLDDIR \
      -DGMX_BUILD_OWN_FFTW=ON  \
      -DCMAKE_BUILD_TYPE=Release \
      -DGMX_GPU=OFF \
      -DGMX_X11=OFF \
      -DGMX_EXTERNAL_BLAS=no \
      -DGMX_EXTERNAL_LAPACK=no \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DGMX_DOUBLE=ON \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DGMX_DEFAULT_SUFFIX=ON

if [ $? -ne 0 ] ; then
  echo "$PACKAGE configure failed"
  exit 1
fi

make
  if [ $? -ne 0 ] ; then
    echo "$PACKAGE make failed"
    exit 1
  fi

make install
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd ..


mkdir buildSerS
cd buildSerS
cmake ../ \
      -DGMX_MPI=OFF \
      -DCMAKE_INSTALL_PREFIX=$SW_BLDDIR \
      -DGMX_BUILD_OWN_FFTW=ON  \
      -DCMAKE_BUILD_TYPE=Release \
      -DGMX_GPU=OFF \
      -DGMX_X11=OFF \
      -DGMX_EXTERNAL_BLAS=no \
      -DGMX_EXTERNAL_LAPACK=no \
      -DGMX_DEFAULT_SUFFIX=OFF \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DGMX_DEFAULT_SUFFIX=ON

if [ $? -ne 0 ] ; then
  echo "$PACKAGE configure failed"
  exit 1
fi

make
  if [ $? -ne 0 ] ; then
    echo "$PACKAGE make failed"
    exit 1
  fi

make install
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd ..

############################### if this far, return 0
exit 0
