#!/bin/bash

############################## standard interface to /sw tools
# Input:
#   Environment variables
#     SW_BLDDIR    current directory (PWD) minus /autofs/na1_ stuff
#     SW_ENVFILE   file to be sourced which has alternate prog environment
#                     only to be used in special circumstances
#     SW_WORKDIR   unique work dir that local script can use
# Output
#   Return code of 0=success or 1=failure 
##############################

# exit 3 is a signal to the sw infrastructure that this template has not 
# been updated; please delete it when ready

if [ -z $SW_BLDDIR ]; then
  echo "Error: SW_BLDDIR not set!"
  exit 1
else
  cd $SW_BLDDIR
fi

if [ -z $SW_ENVFILE ]; then
  ### Set Environment (do not remove this line only change what is in between)
  . ${MODULESHOME}/init/ksh
  . ${SW_BLDDIR}/remodule
  ### End Environment (do not remove this line only change what is in between)
else
  . $SW_ENVFILE
fi

############################## app specific section
#  
set -o verbose
# clear out old installation to prevent potential libtool chmod 
# commands from failing when reinstalled by another person
rm -rf bin lib include doc share man etc libexec info

#clear out status and old SRCDIR file since re-making
rm -f status
rm -rf $SRCDIR

tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$SRCDIR.tar.gz

tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$PREREQ_1.tar.bz2
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$PREREQ_2.tar.gz
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$PREREQ_3.tar.bz2
tar -xf $SW_SOURCES/${PACKAGE}/${VERSION}/$PREREQ_4.tar.bz2

PREREQ_1_BASE=$(echo $PREREQ_1 | awk -F- {'print $1'})
PREREQ_2_BASE=$(echo $PREREQ_2 | awk -F- {'print $1'})
PREREQ_3_BASE=$(echo $PREREQ_3 | awk -F- {'print $1'})
PREREQ_4_BASE=$(echo $PREREQ_4 | awk -F- {'print $1'})

mv $PREREQ_1 $SRCDIR/${PREREQ_1_BASE}
mv $PREREQ_2 $SRCDIR/${PREREQ_2_BASE}
mv $PREREQ_3 $SRCDIR/${PREREQ_3_BASE}
mv $PREREQ_4 $SRCDIR/${PREREQ_4_BASE}

mkdir ${SRCDIR}-objdir

cd ${SRCDIR}-objdir

${SW_BLDDIR}/${SRCDIR}/configure --prefix=$SW_BLDDIR \
--disable-multilib --enable-languages=c,c++,fortran
if [ $? -ne 0 ] ; then
  echo "$PACKAGE configure failed"
  exit 1
fi

make
if [ $? -ne 0 ] ; then
  echo "$PACKAGE make failed"
  exit 1
fi

make install
if [ $? -ne 0 ] ; then
  echo "$PACKAGE install failed"
  exit 1
fi

cd $SW_BLDDIR

############################### if this far, return 0
exit 0
